In [2]:
import numpy as np
import sklearn
import pandas as pd
from sklearn.neighbors import KNeighborsClassifier
from sklearn.feature_extraction.text import CountVectorizer
import math


In [47]:
corpus = [
    "AI is efficient",
    "fast and efficient algorithm",
    "highly accurate and fast",
    "coding AI is challenging",
    "AI may produce errors",
    "unpredictable results",
]

vectorizer = CountVectorizer()
X = vectorizer.fit_transform(corpus)
X = X.toarray()

y_data = np.array([1, 1, 1, 0, 0, 0])

print(X)

[[0 1 0 0 0 0 1 0 0 0 1 0 0 0 0]
 [0 0 1 1 0 0 1 0 1 0 0 0 0 0 0]
 [1 0 0 1 0 0 0 0 1 1 0 0 0 0 0]
 [0 1 0 0 1 1 0 0 0 0 1 0 0 0 0]
 [0 1 0 0 0 0 0 1 0 0 0 1 1 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 1 1]]


In [46]:
data1 = ["AI is accurate and fast"]
x_data1 = vectorizer.transform(data1)
x_data1 = x_data1.toarray()
print(x_data1)

[[1 1 0 1 0 0 0 0 1 0 1 0 0 0 0]]


In [ ]:
# Euclidean distance computation
def computeDistance(dataPoint1, dataPoint2):
    distance = np.sqrt(np.sum((dataPoint1 - dataPoint2) ** 2))
    return distance


data2 = ["coding AI is challenging"]
x_data2 = vectorizer.transform(data2)
x_data2 = x_data2.toarray()

print(x_data2)

[[0 1 0 0 1 1 0 0 0 0 1 0 0 0 0]]


In [24]:
computeDistance(x_data1, x_data2)

np.float64(2.23606797749979)

In [ ]:
data3 = ["highly accurate and fast"]
data4 = ["unpredictable results"]
data5 = ["AI may produce errors"]
data6 = ["AI is efficient"]
data7 = ["fast and efficient algorithm"]

x_data3 = vectorizer.transform(data3)
x_data3 = x_data3.toarray()

x_data4 = vectorizer.transform(data4)
x_data4 = x_data4.toarray()

x_data5 = vectorizer.transform(data5)
x_data5 = x_data5.toarray()

x_data6 = vectorizer.transform(data6)
x_data6 = x_data6.toarray()

x_data7 = vectorizer.transform(data7)
x_data7 = x_data7.toarray()

distance_x1_x3 = computeDistance(x_data1, x_data3)
distance_x1_x4 = computeDistance(x_data1, x_data4)
distance_x1_x5 = computeDistance(x_data1, x_data5)
distance_x1_x6 = computeDistance(x_data1, x_data6)
distance_x1_x7 = computeDistance(x_data1, x_data7)
print(distance_x1_x3, distance_x1_x4, distance_x1_x5, distance_x1_x6, distance_x1_x7)

1.7320508075688772 2.6457513110645907 2.6457513110645907 2.0 2.23606797749979


In [32]:
df = pd.read_csv("my_data.csv")
X_train = df[["perimeter_mean", "area_mean", "compactness_mean"]].values.tolist()
labels = df["diagnosis"].values.tolist()

In [33]:
print(labels)

['B', 'B', 'B', 'B', 'B', 'M', 'M', 'M', 'M', 'M']


In [34]:
y_train = []

for label in labels:
    if label == "B":
        y_train.append(0)
    else:
        y_train.append(1)

print(type(y_train))
print(y_train)


<class 'list'>
[0, 0, 0, 0, 0, 1, 1, 1, 1, 1]


In [36]:
train_data = zip(X_train, y_train)
train_data = list(train_data)
print(train_data)

[([0.28, 0.17, 0.12], 0), ([0.11, 0.06, 0.16], 0), ([0.33, 0.21, 0.2], 0), ([0.26, 0.15, 0.09], 0), ([0.22, 0.09, 0.2], 0), ([0.58, 0.41, 0.47], 1), ([0.57, 0.37, 0.77], 1), ([0.48, 0.38, 0.27], 1), ([0.6, 0.48, 0.37], 1), ([0.54, 0.42, 0.43], 1)]


In [ ]:
def computeDistanceManhattan(x, y):
    distance = np.sum(np.abs(x - y))
    return distance


In [40]:
x = np.array([0.25, 0.25, 0.25])
train_k = X_train[:3]
print(train_k)

[[0.28, 0.17, 0.12], [0.11, 0.06, 0.16], [0.33, 0.21, 0.2]]


In [41]:
distance_mant = []
for data in train_k:
    dis = computeDistanceManhattan(x, data)
    distance_mant.append(dis)

print(distance_mant)

[np.float64(0.24000000000000002), np.float64(0.42000000000000004), np.float64(0.17)]


In [44]:
distance_mant2 = []
for data in X_train:
    dis = computeDistanceManhattan(x, data)
    distance_mant2.append(dis)

dis_all = sorted(distance_mant2)
print(dis_all)

[np.float64(0.17), np.float64(0.24), np.float64(0.24000000000000002), np.float64(0.27), np.float64(0.38), np.float64(0.42000000000000004), np.float64(0.64), np.float64(0.7), np.float64(0.71), np.float64(0.96)]


In [ ]:
corpus = [
    "AI is efficient",
    "fast and efficient algorithm",
    "highly accurate and fast",
    "coding AI is challenging",
    "AI may produce errors",
    "unpredictable results",
]

vectorizer = CountVectorizer()
X = vectorizer.fit_transform(corpus)
X = X.toarray()

# y_data = np.array([1, 1, 1, 0, 0, 0])

centroids1 = np.array([0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0])
centroids2 = np.array([0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0])

for x in corpus:
    x_vec = vectorizer.transform([x])
    x_vec = x_vec.toarray()
    distance = computeDistance(centroids1, x_vec)
    print(x, round(distance, 3))


AI is efficient 0.0
fast and efficient algorithm 2.236
highly accurate and fast 2.646
coding AI is challenging 1.732
AI may produce errors 2.236
unpredictable results 2.236


In [55]:
for x in corpus:
    x_vec = vectorizer.transform([x])
    x_vec = x_vec.toarray()
    distance = computeDistance(centroids2, x_vec)
    print(x, round(distance, 3))

AI is efficient 2.236
fast and efficient algorithm 2.828
highly accurate and fast 2.828
coding AI is challenging 2.449
AI may produce errors 0.0
unpredictable results 2.449


In [ ]:
new_centroid1 = np.array(
    [0.2, 0.4, 0.2, 0.4, 0.2, 0.2, 0.4, 0.0, 0.4, 0.2, 0.4, 0.0, 0.0, 0.2, 0.2]
)
for x in corpus:
    x_vec = vectorizer.transform([x])
    x_vec = x_vec.toarray()
    distance = computeDistance(new_centroid1, x_vec)
    print(x, round(distance, 3))

AI is efficient 1.296
fast and efficient algorithm 1.51
highly accurate and fast 1.637
coding AI is challenging 1.637
AI may produce errors 2.069
unpredictable results 1.51


In [ ]:
!gdown 1z99FO2PE35V2BHGC4oy_qC7iKYDFy8pH

In [68]:

df = pd.read_csv("my_data.csv")
train_data = df[["perimeter_mean", "area_mean", "compactness_mean"]].values.tolist()
labels = df["diagnosis"].values.tolist()

In [69]:
print(labels)
print(train_data)

['B', 'B', 'B', 'B', 'B', 'M', 'M', 'M', 'M', 'M']
[[0.28, 0.17, 0.12], [0.11, 0.06, 0.16], [0.33, 0.21, 0.2], [0.26, 0.15, 0.09], [0.22, 0.09, 0.2], [0.58, 0.41, 0.47], [0.57, 0.37, 0.77], [0.48, 0.38, 0.27], [0.6, 0.48, 0.37], [0.54, 0.42, 0.43]]


In [70]:
c1 = np.array([0.33, 0.21, 0.2])
c2 = np.array([0.6, 0.48, 0.37])


In [73]:
# Phân cụm
cluster1 = []
cluster2 = []
for point in train_data:
    d1 = np.linalg.norm(point - c1)
    d2 = np.linalg.norm(point - c2)

    if d1 < d2:
        cluster1.append(point)
    else:
        cluster2.append(point)

cluster1 = np.array(cluster1)
print(cluster1)

new_centroid1 = cluster1.mean(axis=0)
print("Centroid mới của Cụm 1:", new_centroid1)

cluster2 = np.array(cluster2)
print(cluster2)

new_centroid2 = cluster2.mean(axis=0)
print("Centroid mới của Cụm 2:", new_centroid2)

[[0.28 0.17 0.12]
 [0.11 0.06 0.16]
 [0.33 0.21 0.2 ]
 [0.26 0.15 0.09]
 [0.22 0.09 0.2 ]]
Centroid mới của Cụm 1: [0.24  0.136 0.154]
[[0.58 0.41 0.47]
 [0.57 0.37 0.77]
 [0.48 0.38 0.27]
 [0.6  0.48 0.37]
 [0.54 0.42 0.43]]
Centroid mới của Cụm 2: [0.554 0.412 0.462]


In [66]:
total_d1 = 0
for point in train_data:
    d1 = np.linalg.norm(point - c1)
    total_d1 += d1

print(total_d1)

2.7665581375502875


In [67]:
total_d2 = 0
for point in train_data:
    d2 = np.linalg.norm(point - c2)
    total_d2 += d2

print(total_d2)

3.5573512800012375


In [74]:
cluster1_new=[]
cluster2_new=[]

for point in train_data:
    d1 = np.linalg.norm(point - new_centroid1)
    d2 = np.linalg.norm(point - new_centroid2)

    if d1 < d2:
        cluster1_new.append(point)
    else:
        cluster2_new.append(point)

cluster1_new = np.array(cluster1_new)
print(cluster1_new)

new_centroid1 = cluster1_new.mean(axis=0)
print("Centroid mới của Cụm 1:", new_centroid1)

cluster2_new = np.array(cluster2_new)
print(cluster2_new)

new_centroid2 = cluster2_new.mean(axis=0)
print("Centroid mới của Cụm 2:", new_centroid2)

[[0.28 0.17 0.12]
 [0.11 0.06 0.16]
 [0.33 0.21 0.2 ]
 [0.26 0.15 0.09]
 [0.22 0.09 0.2 ]]
Centroid mới của Cụm 1: [0.24  0.136 0.154]
[[0.58 0.41 0.47]
 [0.57 0.37 0.77]
 [0.48 0.38 0.27]
 [0.6  0.48 0.37]
 [0.54 0.42 0.43]]
Centroid mới của Cụm 2: [0.554 0.412 0.462]


In [10]:
df = pd.read_csv("tennis_v4.csv")
df

Outlook Temperature Humidity    Wind Play_Tennis
0      Sunny        Cool     High    Weak         Yes
1      Sunny        Cool     High  Strong          No
2   Overcast        Mild     High    Weak         Yes
3       Rain         Hot   Normal    Weak         Yes
4       Rain         Hot   Normal  Strong          No
5   Overcast         Hot   Normal  Strong         Yes
6      Sunny        Mild     High    Weak          No
7      Sunny        Cool   Normal    Weak         Yes
8      Sunny         Hot     High  Strong          No
9       Rain        Cool   Normal    Weak         Yes
10      Rain        Cool     High  Strong          No
11     Sunny        Cool   Normal  Strong         Yes
12  Overcast         Hot     High  Strong         Yes
13  Overcast        Mild   Normal    Weak         Yes

In [14]:
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from collections import Counter

In [ ]:
X = df.drop("Play_Tennis", axis=1)
y = df["Play_Tennis"]


11    Yes
12    Yes
13    Yes
Name: Play_Tennis, dtype: object


In [11]:
X = df.iloc[:, :-1].values  # All columns except the last one are features
y = df.iloc[:, -1].values  # The last column is the label
feature_names = df.columns[:-1].tolist()
print(f"Các đặc trưng: {feature_names}")

Các đặc trưng: ['Outlook', 'Temperature', 'Humidity', 'Wind']


In [13]:
X_train, y_train = X[:11], y[:11]
X_test, y_test = X[11:], y[11:]

In [15]:
def calculate_entropy(y):
    # Count the number of occurrences of each label
    label_counts = Counter(y)
    # Calculate the frequency of each label
    label_freqs = np.array(list(label_counts.values())) / len(y)
    # Calculate entropy
    entropy = -np.sum(label_freqs * np.log2(label_freqs))
    return entropy

In [16]:
entropy_root = calculate_entropy(y_train)
print(f"Entropy của tập dữ liệu ban đầu: {entropy_root:.4f}")

Entropy của tập dữ liệu ban đầu: 0.9940


In [17]:
column = "Temperature"
col_idx = feature_names.index(
    column
)  # Index of the column corresponding to the feature

# Unique values & its count in 'Temperature' column
values, count = np.unique(X_train[:, col_idx], return_counts=True)

# Calculate the entropy of each partition
for value in values:
    # Mask to filter rows that have the value of the feature == the unique value
    mask = X_train[:, col_idx] == value
    print(f"Entropy khi {column} = {value}: {calculate_entropy(y_train[mask]):.4f}")

# Calculate the sum of the entropy of each partition
entropy_temperature = np.sum(
    [
        count[i]
        / len(y_train)
        * calculate_entropy(y_train[X_train[:, col_idx] == values[i]])
        for i in range(len(values))
    ]
)
information_gain = entropy_root - entropy_temperature
print(f"Information gain khi chia theo {column}: {information_gain:.4f}")

Entropy khi Temperature = Cool: 0.9710
Entropy khi Temperature = Hot: 1.0000
Entropy khi Temperature = Mild: 1.0000
Information gain khi chia theo Temperature: 0.0072


In [18]:
features = feature_names
information_gains = []
for column in features:
    col_idx = feature_names.index(column)
    values, count = np.unique(X_train[:, col_idx], return_counts=True)
    entropy_feature = np.sum(
        [
            count[i] / len(y_train) * calculate_entropy(y_train[X_train[:, col_idx] == values[i]])
            for i in range(len(values))
        ]
    )
    information_gain = entropy_root - entropy_feature
    information_gains.append(information_gain)
    print(f"Information gain khi chia theo {column}: {information_gain:.4f}")

best_feature_idx = np.argmax(information_gains)
best_feature = features[best_feature_idx]
print(f"Đặc trưng tốt nhất để chia: {best_feature}")

Information gain khi chia theo Outlook: 0.1891
Information gain khi chia theo Temperature: 0.0072
Information gain khi chia theo Humidity: 0.1650
Information gain khi chia theo Wind: 0.3113
Đặc trưng tốt nhất để chia: Wind


In [19]:
import numpy as np
import math
from collections import Counter

# Define the DecisionTree class
class DecisionTree:
    def __init__(self, feature_names):
        self.tree = None
        self.feature_names = feature_names

    def entropy(self, y, node_name=""):
        freq = Counter(y)
        total = len(y)
        entropy_value = -sum(
            (count / total) * math.log2(count / total) for count in freq.values()
        )
        entropy_value = 0 if entropy_value == -0.0 else entropy_value
        if node_name:
            print(
                f"Node: {node_name} | Label Distribution: {dict(freq)} | Entropy: {entropy_value:.4f}"
            )
        return entropy_value

    # Calculate the information gain
    def info_gain(self, X_column, y, node_name):
        total_entropy = self.entropy(y, node_name)
        values, counts = np.unique(X_column, return_counts=True)
        weighted_entropy = sum(
            (counts[i] / sum(counts))
            * self.entropy(y[X_column == values[i]], f"{values[i]}")
            for i in range(len(values))
        )
        info_gain_value = total_entropy - weighted_entropy
        return info_gain_value

    # Determine the best feature to split on based on information gain
    def best_feature_split(self, X, y):
        best_gain = -1
        best_feature = None
        print("\n=== Information Gain for Each Feature ===\n")
        for col in range(X.shape[1]):
            gain = self.info_gain(X[:, col], y, node_name="Total" if col == 0 else "")
            print(f"Feature {self.feature_names[col]}: Information Gain = {gain:.4f}\n")
            if gain > best_gain:
                best_gain = gain
                best_feature = col
        print(
            f"Best feature to split on {self.feature_names[best_feature]} with Information Gain: {best_gain:.4f}\n"
        )
        return best_feature

    # Fit the model and build the tree
    def fit(self, X, y, feature_names, depth=0):

        print(f"\n--- Building Tree at Depth {depth} ---")
        if len(set(y)) == 1:
            print(f"Stopping condition met at depth {depth}, class: {y[0]}")
            return y[0]

        if X.shape[1] == 0:
            most_common = Counter(y).most_common(1)[0][0]
            print(
                f"No more features to split on at depth {depth}, returning majority class: {most_common}"
            )
            return most_common

        feature_idx = self.best_feature_split(X, y)
        best_feature_name = feature_names[feature_idx]
        tree = {best_feature_name: {}}
        print(f"=> Splitting on feature {best_feature_name} at depth {depth}\n")

        # Split the dataset based on the best feature
        for value in np.unique(X[:, feature_idx]):
            sub_X = X[X[:, feature_idx] == value]
            sub_y = y[X[:, feature_idx] == value]
            print()
            print(f"="*45)
            print(f"|| Subtree for feature {best_feature_name} = {value} ||")
            print(f"="*45)
            sub_X = np.delete(sub_X, feature_idx, axis=1)
            new_feature_names = (
                feature_names[:feature_idx] + feature_names[feature_idx + 1 :]
            )
            tree[best_feature_name][value] = self.fit(
                sub_X, sub_y, new_feature_names, depth + 1
            )

        self.tree = tree
        return tree

    # Predict the class labels for the samples
    def predict(self, X):
        def classify(tree, sample):
            if not isinstance(tree, dict):
                return tree
            feature = list(tree.keys())[0]
            feature_idx = self.feature_names.index(feature)
            value = sample[feature_idx]

            # Check if the feature value is missing ("")
            if value == "":
                print(
                    f"Feature '{feature}' is missing in the sample so the model can't predict"
                )

            # Find the subtree or return None if the feature is required and not found
            subtree = tree[feature].get(value, None)
            if subtree is None:
                return None  # If we can't find the path, return None

            if isinstance(subtree, dict):
                return classify(subtree, sample)
            else:
                return subtree

        # Apply classification for all samples in X
        return (
            np.array([classify(self.tree, x) for x in X])
            if len(X.shape) > 1
            else classify(self.tree, X)
        )

    # Function to print the tree
    def visualize(self):
        def print_tree(node_name, node_values, depth):
            for value in node_values:
                if isinstance(node_values[value], dict):
                    print(f"{'|  ' * depth}{node_name} = {value}")
                    sub_tree = node_values[value]
                    new_node = list(sub_tree.keys())[0]
                    print_tree(new_node, sub_tree[new_node], depth + 1)
                else:
                    print(f"{'|  ' * depth}{node_name} = {value}: {node_values[value]}")

        if self.tree:
            root_node = list(self.tree.keys())[0]
            print("\n--- Decision Tree ---")
            print_tree(root_node, self.tree[root_node], 0)

In [20]:
tree = DecisionTree(feature_names)
tree.fit(X_train, y_train, feature_names)
tree.visualize()


--- Building Tree at Depth 0 ---

=== Information Gain for Each Feature ===

Node: Total | Label Distribution: {'Yes': 6, 'No': 5} | Entropy: 0.9940
Node: Overcast | Label Distribution: {'Yes': 2} | Entropy: 0.0000
Node: Rain | Label Distribution: {'Yes': 2, 'No': 2} | Entropy: 1.0000
Node: Sunny | Label Distribution: {'Yes': 2, 'No': 3} | Entropy: 0.9710
Feature Outlook: Information Gain = 0.1891

Node: Cool | Label Distribution: {'Yes': 3, 'No': 2} | Entropy: 0.9710
Node: Hot | Label Distribution: {'Yes': 2, 'No': 2} | Entropy: 1.0000
Node: Mild | Label Distribution: {'Yes': 1, 'No': 1} | Entropy: 1.0000
Feature Temperature: Information Gain = 0.0072

Node: High | Label Distribution: {'Yes': 2, 'No': 4} | Entropy: 0.9183
Node: Normal | Label Distribution: {'Yes': 4, 'No': 1} | Entropy: 0.7219
Feature Humidity: Information Gain = 0.1650

Node: Strong | Label Distribution: {'No': 4, 'Yes': 1} | Entropy: 0.7219
Node: Weak | Label Distribution: {'Yes': 5, 'No': 1} | Entropy: 0.6500
Feat

In [21]:
y_test_pred = tree.predict(X_test)
print(f"Predict test set: {y_test_pred}")
print(f"Actual test set: {y_test}")

accuracy = np.mean(y_test_pred == y_test)
print(f"Accuracy: {accuracy:.2f}")

Predict test set: ['No' 'Yes' 'Yes']
Actual test set: ['Yes' 'Yes' 'Yes']
Accuracy: 0.67


In [1]:
import torch
print("CUDA:", torch.cuda.is_available())          # sẽ trả về False trên Apple Silicon
print("MPS:", torch.backends.mps.is_available())   # True nếu PyTorch được cài với support MPS


CUDA: False
MPS: True
