In [4]:
import numpy as np

data = np.random.rand(64, 2)
print(data.shape)

centroids = np.random.rand(5, 2)
print(centroids.shape)

distances = data - centroids
print(distances.shape)

(64, 2)
(5, 2)


ValueError: operands could not be broadcast together with shapes (64,2) (5,2) 

In [6]:
import numpy as np
import pandas as pd

data = pd.read_csv("./data/iris_1D.csv")
data

Petal_Length  Label
0           1.4    0.0
1           1.0    0.0
2           1.5    0.0
3           3.1    1.0
4           3.8    1.0
5           4.1    1.0

In [ ]:
# X = np.array(data["Petal_Length"])
X = data["Petal_Length"].to_numpy()
print(X)

[1.4 1.  1.5 3.1 3.8 4.1]


In [28]:
centroids = np.array([1.4, 1.0])


In [ ]:
distances = np.abs(X.reshape(-1, 1) - centroids)
distances

array([[0. , 0.3],
       [0.4, 0.1],
       [0.1, 0.4],
       [1.7, 2. ],
       [2.4, 2.7],
       [2.7, 3. ]])

In [19]:
labels = np.argmin(distances, axis=1)
print(labels)

[0 1 0 0 0 0]


In [20]:
X

array([1.4, 1. , 1.5, 3.1, 3.8, 4.1])

In [ ]:
centroids = np.array([X[labels == i].mean() for i in range(2)])
centroids

array([2.78, 1.  ])

In [ ]:
# Sau khi có centroids mới thì quay lại bước tính distances -> labels -> centroids
distances = np.abs(X.reshape(-1, 1) - centroids)
distances

array([[1.38, 0.4 ],
       [1.78, 0.  ],
       [1.28, 0.5 ],
       [0.32, 2.1 ],
       [1.02, 2.8 ],
       [1.32, 3.1 ]])

In [23]:
labels = np.argmin(distances, axis=1)
print(labels)

[1 1 1 0 0 0]


In [24]:
centroids = np.array([X[labels == i].mean() for i in range(2)])
centroids

array([3.66666667, 1.3       ])

In [25]:
distances = np.abs(X.reshape(-1, 1) - centroids)
labels = np.argmin(distances, axis=1)
print(labels)

[1 1 1 0 0 0]


In [26]:
centroids = np.array([X[labels == i].mean() for i in range(2)])
centroids

array([3.66666667, 1.3       ])

In [27]:
centroids = X[:2]
for _ in range(10):
    distances = np.abs(X.reshape(-1, 1) - centroids)
    labels = np.argmin(distances, axis=1)
    new_centroids = np.array([X[labels == i].mean() for i in range(2)])

    if np.all(centroids == new_centroids):
        break

    centroids = new_centroids
    # print
    print("Labels:", labels)
    print("Centroids:", centroids)
    print()


Labels: [0 1 0 0 0 0]
Centroids: [2.78 1.  ]

Labels: [1 1 1 0 0 0]
Centroids: [3.66666667 1.3       ]



In [ ]:
from sklearn.cluster import KMeans

kmeans = KMeans(n_clusters=2)
kmeans.fit(X.reshape(-1, 1))
labels = kmeans.labels_
print(labels)
print(kmeans.inertia_)

for x, label in zip(X, labels):
    print(f"Cluster {label}: {x}")


[1 1 1 0 0 0]
0.6666666666666662
Cluster 1: 1.4
Cluster 1: 1.0
Cluster 1: 1.5
Cluster 0: 3.1
Cluster 0: 3.8
Cluster 0: 4.1


In [34]:
X= np.random.rand(3)
C = np.random.rand(2)
distances = X.reshape(3,1) - C

In [2]:
import cv2
import os
import numpy as np

def load_images_from_folder(folder):
    data = []
    for filename in os.listdir(folder):
        if filename.lower().endswith('.jpg'):
            img= cv2.imread(os.path.join(folder, filename))
            data.append(img)

    return data

dog_images = load_images_from_folder("./data/training/dog/")
cat_images = load_images_from_folder("./data/training/cat/")

In [4]:
dog_images[0].shape

(224, 224, 3)

In [5]:
dog_images = np.array(dog_images)
cat_images = np.array(cat_images)

In [6]:
dog_images.shape

(10, 224, 224, 3)

In [8]:
# merge dog and cat image features
merged_features = np.concatenate((dog_images.reshape(10, -1), cat_images.reshape(10, -1) ), axis=0)
merged_features.shape

(20, 150528)

In [9]:
from sklearn.cluster import KMeans
kmeans = KMeans(n_clusters=2).fit(merged_features)
print(kmeans.labels_)

[0 1 0 1 0 0 1 0 0 1 0 0 1 1 0 0 1 1 1 1]


/Users/vychan/Coding/AIO2025/Code/aio2025_study/venv/lib/python3.13/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: divide by zero encountered in matmul
  ret = a @ b
/Users/vychan/Coding/AIO2025/Code/aio2025_study/venv/lib/python3.13/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: overflow encountered in matmul
  ret = a @ b
/Users/vychan/Coding/AIO2025/Code/aio2025_study/venv/lib/python3.13/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: invalid value encountered in matmul
  ret = a @ b
