In [2]:
import torch
import torch.nn as nn

torch.manual_seed(123)

### Convolutional Layer

In [ ]:
# Khởi tạo input đầu vào
input = torch.randint(10, (1, 6, 6), dtype=torch.float32)
input

tensor([[[1., 8., 0., 5., 4., 1.],
         [6., 7., 3., 1., 2., 2.],
         [8., 8., 3., 3., 4., 6.],
         [1., 2., 3., 6., 0., 5.],
         [0., 5., 2., 9., 4., 0.],
         [4., 8., 1., 2., 6., 9.]]])

In [13]:
input.shape

torch.Size([1, 6, 6])

In [ ]:
# Convolutional layer không có bias
conv_layer = nn.Conv2d(in_channels=1, out_channels=1, kernel_size=3, bias=False)

In [ ]:
# Weight của kernel tự sinh ra bởi thư viện
conv_layer.weight

Parameter containing:
tensor([[[[-0.2360, -0.2687,  0.1384],
          [ 0.0075,  0.1366, -0.3257],
          [-0.0199,  0.2351,  0.1546]]]], requires_grad=True)

In [ ]:
conv_layer.bias  # Vì ở đây không có bias nên sẽ trả về None

In [ ]:
# Có thể gán lại weight bằng cách:
init_kernel_weight = torch.randint(
    high=2, size=(conv_layer.weight.data.shape), dtype=torch.float32
)
conv_layer.weight.data = init_kernel_weight

conv_layer.weight

Parameter containing:
tensor([[[[0., 1., 0.],
          [0., 1., 1.],
          [1., 0., 1.]]]], requires_grad=True)

In [12]:
output = conv_layer(input)
output

tensor([[[29., 15., 15., 17.],
         [22., 17., 11., 23.],
         [15., 26., 15., 18.],
         [14., 24., 26., 15.]]], grad_fn=<SqueezeBackward1>)

In [14]:
output.shape

torch.Size([1, 4, 4])

In [ ]:
# Convolutional layer có bias
conv_layer_bias = nn.Conv2d(1, 1, kernel_size=3)
conv_layer_bias.bias.data

tensor([0.0255])

In [21]:
conv_layer_bias.weight.data = init_kernel_weight

In [22]:
output_with_bias = conv_layer_bias(input)
output_with_bias

tensor([[[29.0255, 15.0255, 15.0255, 17.0255],
         [22.0255, 17.0255, 11.0255, 23.0255],
         [15.0255, 26.0255, 15.0255, 18.0255],
         [14.0255, 24.0255, 26.0255, 15.0255]]], grad_fn=<SqueezeBackward1>)

In [30]:
# Convolutional layer với kernel không đều
conv_layer_uneven = nn.Conv2d(1, 1, kernel_size=(2, 3))
conv_layer_uneven.weight.data = init_kernel_weight
print(conv_layer_uneven.bias.data)

output_uneven = conv_layer_uneven(input)
output_uneven

tensor([0.1679])


tensor([[[29.1679, 15.1679, 15.1679, 17.1679],
         [22.1679, 17.1679, 11.1679, 23.1679],
         [15.1679, 26.1679, 15.1679, 18.1679],
         [14.1679, 24.1679, 26.1679, 15.1679]]], grad_fn=<SqueezeBackward1>)

In [26]:
# Convolutional layer với padding
conv_layer_with_padding = nn.Conv2d(1,1,kernel_size=3,padding=1)
conv_layer_with_padding.weight.data = init_kernel_weight

output_with_padding = conv_layer_with_padding(input)
output_with_padding.shape

torch.Size([1, 6, 6])