In [ ]:
import numpy as np

arr1 = np.array([[1, 2], [3, 4]])

arr1.size

4

In [ ]:
arr2 = np.array([[1, 2, 3, 4], [3, 4, 5, 6], [5, 6, 7, 8]])
arr2.shape

(3, 4)

In [11]:
# Tạo mảng 1 chiều với 5 phần tử
arr3 = np.zeros(5)
print(arr3)

[0. 0. 0. 0. 0.]


In [ ]:
# Tạo mảng 2 chiều với 3 phần tử mỗi chiều
arr4 = np.zeros((2, 3))
print(arr4)

[[0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
# Tạo mảng 2 chiều với 3 phần tử mỗi chiều
arr5 = np.zeros((3, 2))
print(arr5)

[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [ ]:
import numpy as np

data = np.array([1, 2])

np.repeat(data, 4)

TypeError: order must be str, not tuple

In [ ]:
data = np.arange(6).reshape(2, 3)
print(data)

data[:, 1]

[[0 1 2]
 [3 4 5]]


array([1, 4])

In [ ]:
data = np.array([1, 8, 3, 9, 7, 6])

data[data >= 7]

array([8, 9, 7])

In [ ]:
data = np.arange(3, 7)
print(data)
out = data[[0, 1, 3, 2]]
print(out)

[3 4 5 6]
[3 4 6 5]


In [ ]:
data = np.arange(9).reshape(3, 3)
data[:, [1, 0, 2]]
print(data)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
data[:, [1, 0, 2]]

array([[1, 0, 2],
       [4, 3, 5],
       [7, 6, 8]])

In [ ]:
data = np.arange(9).reshape(3, 3)
data[[2, 1, 0], :]

array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

In [ ]:
data = np.arange(9).reshape(3, 3)
data[::-1, :]

array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

In [ ]:
data = np.arange(16).reshape(4, 4)
data[:3, 2:]

array([[ 2,  3],
       [ 6,  7],
       [10, 11]])

In [ ]:
data = np.arange(9).reshape(3, 3)
slicing_data = data[:2, 1:]
slicing_data = slicing_data * 3
print(slicing_data)

[[ 3  6]
 [12 15]]


In [ ]:
data = np.arange(10)

# 3 cái này giống nhau
# data.reshape(2,5)
# data.reshape(-1,5)
# data.reshape(2,-1)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [ ]:
data1 = np.array([1, 2, 3])
data2 = np.array([[1], [2], [3]])
data = data1 + data2
print(data)

[[2 3 4]
 [3 4 5]
 [4 5 6]]


In [ ]:
import numpy as np

listND = [
    [[[1], [2], [3], [4], [5]], [[1], [2], [3], [4], [5]], [[1], [2], [3], [4], [5]]],
    [[[1], [2], [3], [4], [5]], [[1], [2], [3], [4], [5]], [[1], [2], [3], [4], [5]]],
    [[[1], [2], [3], [4], [5]], [[1], [2], [3], [4], [5]], [[1], [2], [3], [4], [5]]],
    [[[1], [2], [3], [4], [5]], [[1], [2], [3], [4], [5]], [[1], [2], [3], [4], [5]]],
]
data = np.array(listND)
print(data.shape)

(4, 3, 5, 1)


In [ ]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

In [ ]:
np.vstack((arr1, arr2))

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
np.hstack((arr1, arr2))

array([1, 2, 3, 4, 5, 6])

In [16]:
np.concatenate((arr1, arr2), axis=0)

array([1, 2, 3, 4, 5, 6])

In [ ]:
data = np.array([4, 1, 7, 2])
result = data[data % 2 == 0]
print(result)

[4 2]


In [ ]:
x = np.array([1, 2, 3])
print(x)

[1 2 3]


In [20]:
m = x.max()
print(m)

3


In [26]:
x = x - m
print(x)

[-2 -1  0]


In [27]:
exp_x = np.exp(x)
print(exp_x)

[0.13533528 0.36787944 1.        ]


In [28]:
total = np.sum(exp_x)
print(total)

1.5032147244080551


In [29]:
softmax_x = exp_x / total
print(softmax_x)

[0.09003057 0.24472847 0.66524096]
