In [ ]:
import numpy as np

arr1 = np.array([[1,2],[3,4]])

arr1.size

4

In [10]:
arr2 = np.array([[1,2,3,4],[3,4,5,6],[5,6,7,8]])
arr2.shape


(3, 4)

In [11]:
# Tạo mảng 1 chiều với 5 phần tử
arr3 = np.zeros(5)
print(arr3)

[0. 0. 0. 0. 0.]


In [13]:
# Tạo mảng 2 chiều với 3 phần tử mỗi chiều
arr4 = np.zeros((2,3))
print(arr4)

[[0. 0. 0.]
 [0. 0. 0.]]


In [14]:
# Tạo mảng 2 chiều với 3 phần tử mỗi chiều
arr5 = np.zeros((3,2))
print(arr5)

[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [ ]:
import numpy as np
data = np.array([1,2])

np.repeat(data,4)

TypeError: order must be str, not tuple

In [25]:
data = np.arange(6).reshape(2,3)
print(data)

data[:,1]

[[0 1 2]
 [3 4 5]]


array([1, 4])

In [27]:
data = np.array([1,8,3,9,7,6])

data[data>=7]

array([8, 9, 7])

In [29]:
data = np.arange(3,7)
print(data)
out = data[[0,1,3,2]]
print(out)

[3 4 5 6]
[3 4 6 5]


In [ ]:
data = np.arange(9).reshape(3,3)
data[:,[1,0,2]]
print(data)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [31]:
data[:,[1,0,2]]

array([[1, 0, 2],
       [4, 3, 5],
       [7, 6, 8]])

In [32]:
data = np.arange(9).reshape(3,3)
data[[2,1,0],:]

array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

In [33]:
data = np.arange(9).reshape(3,3)
data[::-1,:]

array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

In [34]:
data = np.arange(16).reshape(4,4)
data[:3,2:]

array([[ 2,  3],
       [ 6,  7],
       [10, 11]])

In [35]:
data = np.arange(9).reshape(3,3)
slicing_data = data[:2,1:]
slicing_data = slicing_data*3
print(slicing_data)

[[ 3  6]
 [12 15]]


In [ ]:
data = np.arange(10)

# 3 cái này giống nhau
# data.reshape(2,5)
# data.reshape(-1,5)
# data.reshape(2,-1)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [40]:
data1 = np.array([1,2,3])
data2 = np.array([[1],[2],[3]])
data = data1 + data2
print(data)

[[2 3 4]
 [3 4 5]
 [4 5 6]]
