In [2]:
import numpy as np

In [5]:
z = np.array([2.0, 1.0, 0.1])
def softmax(z):
    exp_z = np.exp(z)
    return exp_z / sum(exp_z)
print(softmax(z))

[0.65900114 0.24243297 0.09856589]


In [7]:
temperature = 2
def softmax_temperature(z, temperature):
    exp_z_t = np.exp(z/temperature)
    return exp_z_t/sum(exp_z_t)

print(softmax_temperature(z, temperature))

[0.50168776 0.30428901 0.19402324]


In [8]:
z = np.array([2, 0])
print(softmax(z))
print(softmax(z/2))

[0.88079708 0.11920292]
[0.73105858 0.26894142]


In [10]:
z = np.array([3, 1, 0])
exp_z = np.exp(z)
print(exp_z)
print(sum(exp_z))
print(exp_z/sum(exp_z))

[20.08553692  2.71828183  1.        ]
23.803818751646713
[0.84379473 0.1141952  0.04201007]


In [11]:
print(softmax([1.0, 1.0, 1.0]))

[0.33333333 0.33333333 0.33333333]


In [13]:
print(softmax_temperature(np.array([2,1,0]), 10))

[0.3671654  0.33222499 0.30060961]
