In [32]:
import torch
import numpy as np

In [33]:
# Create 2 tensors
x = torch.tensor([1.0, 2.0, 3.0, 4.0])
y = torch.tensor([5.0, 5.0, 5.0, 5.0])

# Compute square difference
mse_loss = torch.nn.MSELoss()
result = mse_loss(x, y)
print(result)

tensor(7.5000)


In [34]:
x = torch.tensor(
    2.0, requires_grad=True
)  # muốn thay đổi bản thân giá trị của nó thì phải có required_grad = true

y = x**2
z = 3 * y + 2
print(f"z: {z}")

z.backward()

print(f"Gradient of z w.r.t x: {x.grad}")

z: 14.0
Gradient of z w.r.t x: 12.0


In [35]:
from torch.autograd import Variable

x = torch.tensor([3.0])
x = Variable(x, requires_grad=True)
y = x**2
z = 3 * y + 2

z.backward()  # compute gradient

print(f"z: {z}")
print(f"Gradient of z w.r.t x: {x.grad}")

z: tensor([29.], grad_fn=<AddBackward0>)
Gradient of z w.r.t x: tensor([18.])


In [36]:
# tensor là dữ liệu nhiều chiều, nó có thể là bất kỳ chiều nào

torch.__version__

'2.9.1'

In [37]:
import torch.optim as optim

x = torch.tensor([[1.0, 1.0], [1.0, 1.0]])
x = x.requires_grad_(True)

y = x**2
z = 3 * y + 2

opt = optim.SGD([x], lr=0.1)
opt.zero_grad()  # Xoá gradient cũ
z.backward(torch.ones_like(z))

opt.step()

print(x)

tensor([[0.4000, 0.4000],
        [0.4000, 0.4000]], requires_grad=True)


In [38]:
import torch.nn as nn

# Linear layer
linear_layer = nn.Linear(4, 1)  # (x, y) : x-> node input, y->node output

print(f"b - {linear_layer.bias}")
print(f"w - {linear_layer.weight}")

# mỗi lần chạy nó sẽ sinh ra 1 tham số, tạo ra các theta khác nhau

b - Parameter containing:
tensor([0.0840], requires_grad=True)
w - Parameter containing:
tensor([[-0.3390, -0.0412,  0.0885, -0.3431]], requires_grad=True)


In [39]:
linear_layer = nn.Linear(1, 1)
opt = optim.SGD(linear_layer.parameters(), lr=0.01)
loss_fn = torch.nn.MSELoss()

# set values
linear_layer.bias.data = torch.tensor([0.04])
linear_layer.weight.data = torch.tensor([[-0.34]])

x = torch.tensor([6.7])
y_hat = linear_layer(x)
print(y_hat)

y = torch.tensor([9.1])
loss = loss_fn(y_hat, y)
print(loss)

loss.backward()
print(linear_layer.bias.grad)
print(linear_layer.weight.grad)

opt.step()

print(linear_layer.bias)
print(linear_layer.weight)

tensor([-2.2380], grad_fn=<ViewBackward0>)
tensor(128.5502, grad_fn=<MseLossBackward0>)
tensor([-22.6760])
tensor([[-151.9292]])
Parameter containing:
tensor([0.2668], requires_grad=True)
Parameter containing:
tensor([[1.1793]], requires_grad=True)


In [40]:
y_hat = linear_layer(x)
loss = loss_fn(y_hat, y)
print(y_hat)
print(loss)

tensor([8.1680], grad_fn=<ViewBackward0>)
tensor(0.8686, grad_fn=<MseLossBackward0>)


In [41]:
linear_layer = nn.Linear(2, 1)
linear_layer.weight.data = torch.tensor([[0.5, -0.1]])
linear_layer.bias.data = torch.tensor([0.1])

x = torch.tensor([[1.5, 0.2], [4.1, 1.3]])
z = linear_layer(x)
print(z)

sigmoid_layer = nn.Sigmoid()
y_hat = sigmoid_layer(z)
print(y_hat)

tensor([[0.8300],
        [2.0200]], grad_fn=<AddmmBackward0>)
tensor([[0.6964],
        [0.8829]], grad_fn=<SigmoidBackward0>)


In [42]:
bce_loss = nn.BCELoss()
y = torch.tensor([[0], [1]]).float()

loss = bce_loss(y_hat, y)
print(loss)

tensor(0.6582, grad_fn=<BinaryCrossEntropyBackward0>)


In [43]:
optimizer = torch.optim.SGD(linear_layer.parameters(), lr=0.01)
optimizer.zero_grad()
loss.backward()

print(linear_layer.weight.grad)
print(linear_layer.bias.grad)
print(linear_layer.weight)
print(linear_layer.bias)

tensor([[ 0.2822, -0.0065]])
tensor([0.2896])
Parameter containing:
tensor([[ 0.5000, -0.1000]], requires_grad=True)
Parameter containing:
tensor([0.1000], requires_grad=True)


In [44]:
optimizer.step()

print(linear_layer.weight)
print(linear_layer.bias)

Parameter containing:
tensor([[ 0.4972, -0.0999]], requires_grad=True)
Parameter containing:
tensor([0.0971], requires_grad=True)


In [48]:
# Softmax Regression
linear_layer = nn.Linear(1, 2)
linear_layer.weight.data = torch.tensor([[0.2], [-0.1]])
linear_layer.bias.data = torch.tensor([0.1, 0.05])

x = torch.tensor([[1.4]]).float()
z = linear_layer(x)
print(z)

tensor([[ 0.3800, -0.0900]], grad_fn=<AddmmBackward0>)


In [49]:
ce_loss = nn.CrossEntropyLoss()
y = torch.tensor([0])
loss = ce_loss(z, y)
print(loss)

tensor(0.4855, grad_fn=<NllLossBackward0>)


In [51]:
optimizer = torch.optim.SGD(linear_layer.parameters(), lr=0.1)
optimizer.zero_grad()
loss.backward()
print(linear_layer.weight.grad)
print(linear_layer.bias.grad)
optimizer.step()
print(linear_layer.weight)
print(linear_layer.bias)

tensor([[-0.5385],
        [ 0.5385]])
tensor([-0.3846,  0.3846])
Parameter containing:
tensor([[ 0.2538],
        [-0.1538]], requires_grad=True)
Parameter containing:
tensor([0.1385, 0.0115], requires_grad=True)
