In [1]:
import numpy as np

In [4]:
x = np.ones((4,1))
y = np.ones((4,))
print(x.shape)
print(y.shape)
print(x)
print(y)
z = x-y
print(z)

(4, 1)
(4,)
[[1.]
 [1.]
 [1.]
 [1.]]
[1. 1. 1. 1.]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [7]:
x = np.array([[1, 2], [3, 4]])  # x là ma trận 2x2
y = np.array([[3, 4], [5, 6]])

print(x.dot(y))
print(x.T.dot(y))
print(x.dot(y.T))

[[13 16]
 [29 36]]
[[18 22]
 [26 32]]
[[11 17]
 [25 39]]


In [8]:
print(np.vstack([np.zeros((2,)), np.ones((2,))]))
print(np.hstack([np.zeros((2,)), np.ones((2,))]))
print(np.vstack([np.zeros((2,1)), np.ones((2,1))]))
print(np.hstack([np.zeros((2,1)), np.ones((2,1))]))

[[0. 0.]
 [1. 1.]]
[0. 0. 1. 1.]
[[0.]
 [0.]
 [1.]
 [1.]]
[[0. 1.]
 [0. 1.]]


In [ ]:
theta = np.array([0.34, 0.02])
x = np.array([[4,6],[1,1]])

print(theta.T.dot(x))
print(theta.dot(x))
print(theta.dot(x.T))

# Note: Phép chuyển vị .T không làm thay đổi shape của mảng 1 chiều. Do đó theta.T và. theta được Numpy xử lý như nhau

[1.38 2.06]
[1.38 2.06]
[1.48 0.36]
